web:
    build: .
    volumes:
        - .:/usr/local/go/src/github.com/NarrativeTeam/shawty/
    environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_SSL=false
    ports:
        - "8081:8080"
    links:
        - postgres

postgres:
    image: postgres
